# Fresh Trigger
name: Sentinel Compliance

on:
  push:
  pull_request:

jobs:
  sentinel:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Sentinel scan
        uses: MOXO08/sentinel-scan-action@v1
        with:
          manifest: "./manifest.json"
          enforce: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
